version: 1.0.{build}
build:
  project: СпециальноДляAppveyor.sln
  verbosity: minimal
before_build:
- cmd: nuget restore СпециальноДляAppveyor.sln
after_build:
- cmd: nuget pack СпециальноДляAppveyor\СпециальноДляAppveyor.nuspec -Version %APPVEYOR_BUILD_VERSION% -Properties "CONFIGURATION=%CONFIGURATION%"
artifacts:
- path: '*.nupkg' 