version: 1.0.{build}

init:
- REG ADD "HKLM\Software\Microsoft\Command Processor" /v Autorun /t REG_SZ /d "chcp 65001>nul" /f

configuration: Release

build:
  project: СпециальноДляAppveyor.sln
  verbosity: minimal
  
before_build:
- cmd: nuget restore

after_build:
- cmd: nuget pack СпециальноДляAppveyor\СпециальноДляAppveyor.nuspec -Version %APPVEYOR_BUILD_VERSION% -Properties "CONFIGURATION=%CONFIGURATION%"
artifacts:
- path: '*.nupkg' 
